---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-what-are-file-permissions"
      label: "What Are File Permissions"
    - name: "02-interacting-with-different-users"
      label: "Interacting With Different Users"
    - name: "03-modifying-permissions"
      label: "Modifying Permissions"
    - name: "04-modifying-absolute"
      label: "Modifying Absolute"
    - name: "05-changing-ownership"
      label: "Changing Ownership"
    - name: "06-changing-group-ownership"
      label: "Changing Group Ownership"
    - name: "07-find-audit-permissions"
      label: "Find Audit Permissions"

tabs:
  - name: ">_ terminal"
    url: /wetty
