---
antora:
  name: modules
  dir: www
  modules:
    - name: "01-what-are-file-permissions"
      label: "What Are File Permissions"
    - name: "02-interacting-with-different-users"
      label: "Interacting With Different Users"
    - name: "03-chmod-command"
      label: "The chmod Command"
    - name: "04-modifying-permissions"
      label: "Modifying Permissions"
    - name: "05-modifying-absolute"
      label: "Modifying Absolute"
    - name: "06-changing-ownership"
      label: "Changing Ownership"
    - name: "07-changing-group-ownership"
      label: "Changing Group Ownership"
    - name: "08-find-audit-permissions"
      label: "Find Audit Permissions"

tabs:
  - name: ">_ root"
    url: /wetty/ssh/root
    secondary_name: ">_ rhel"
    secondary_url: /wetty
